<h1><center>  lab 5 : Text Vectorization - Part 2 </center>
    
<img src="https://miro.medium.com/max/897/0*hcWVsMExgGQJWpt1" width="500">


```Created by Jinnie Shin (jinnie.shin@coe.ufl.edu)```\
```Date: ```

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmNf86oJnfhpkPA9LnrFnAbfwF2VywPYpB_w&usqp=CAU" align="left" width="70" height="70" align="left"> 

 ### Required Packages or Dependencies

In [3]:
#!pip install nbimporter #run this if you run into an error (download nbimporter)
import pandas as pd 
import numpy as np 
import nltk 
nltk.download(['punkt', 'wordnet', 'omw-1.4'])

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/jinnie.shin/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/jinnie.shin/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/jinnie.shin/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True


## **REVIEW**: Dataset

> Using the text_normalizer function we created last time, we will import `essay set 5`

In [4]:
class text_normalize():
    
    def import_data(self, essay_set=3):
        import numpy as np
        import pandas as pd
        self.essay_set = essay_set
        self.data = []
        self.score = []
        filename = 'training_set_rel3.xlsx'
        data = pd.read_excel(filename)
        self.data  = data[data['essay_set']==self.essay_set].essay.values 
        self.score = data[data['essay_set']==self.essay_set].domain1_score.values 
       
        return [' '.join(i) for i in self.data], pd.DataFrame(list(zip(self.data, self.score)), columns=['response', 'score'])
    
    def cleaning(self, string):
        import re
        string  = string.lower() # step 1. lowercase

        punc = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' # step 2. remove punctuations 
        string  = string.strip(punc) 

        string  = string.replace("can't", 'cannot') # step 3. replace abbreviated forms 
        string = string.replace("n't", ' not')
        string  = string.replace("'ll", ' will')
        string  = string.replace("'m", ' am')
        string = string.replace("he's", "he is")
        string = string.replace("it's", 'it is')

        return re.sub(r"\d+", "<DIGIT>", string) # step 4. replace all the numbers to <DIGIT>

    def sent_tokenize(self, string):
        import nltk
        return nltk.sent_tokenize(string)
    
    def tokenize(self, string):
        import nltk
        return nltk.word_tokenize(string)

    def stemming(self, tokens):
        import nltk
        stemmer = nltk.stem.PorterStemmer()
        return [stemmer.stem(token) for token in tokens]
    
    def lemmatize(self, tokens):
        import nltk
        lemmatizer = nltk.stem.WordNetLemmatizer()
        return [lemmatizer.lemmatize(token) for token in tokens]
    
    def preprocess(self, essay_set=1):
        _, self.df = self.import_data(essay_set=essay_set)
        self.df['tokens'] = self.df.response.apply(self.tokenize)
        self.df['sentences'] = self.df.response.apply(self.sent_tokenize)
        self.df['stem'] = self.df.tokens.apply(self.stemming)
        self.df['lemma'] = self.df.tokens.apply(self.lemmatize)

        return self.df 

normalizer = text_normalize() # call the text_normalize function and name it normalizer

df = normalizer.preprocess(5)

In [5]:
df

response  score  \
0     In this memoir of Narciso Rodriguez, @PERSON3'...    2.0   
1     Throughout the excerpt from Home the Blueprint...    2.0   
2     The mood the author created in the memoir is l...    3.0   
3     The mood created by the author is showing how ...    1.0   
4     The mood created in the memoir is happiness an...    3.0   
...                                                 ...    ...   
1800  The mood of this memoir is nonfiction. The moo...    2.0   
1801  The mood was created by the author in the memo...    0.0   
1802  In the memoir "Narciso Rodriguez", the mood cr...    4.0   
1803  The mood created @CAPS3 the author, Narciso Ro...    3.0   
1804  The author created such a specific mood for th...    2.0   

                                                 tokens  \
0     [In, this, memoir, of, Narciso, Rodriguez, ,, ...   
1     [Throughout, the, excerpt, from, Home, the, Bl...   
2     [The, mood, the, author, created, in, the, mem...   
3     [The, mood, created, by, the, author, is, show...   
4     [The, mood, created, in, the, memoir, is, happ...   
...                                                 ...   
1800  [The, mood, of, this, memoir, is, nonfiction, ...   
1801  [The, mood, was, created, by, the, author, in,...   
1802  [In, the, memoir, ``, Narciso, Rodriguez, '', ...   
1803  [The, mood, created, @, CAPS3, the, author, ,,...   
1804  [The, author, created, such, a, specific, mood...   

                                              sentences  \
0     [In this memoir of Narciso Rodriguez, @PERSON3...   
1     [Throughout the excerpt from Home the Blueprin...   
2     [The mood the author created in the memoir is ...   
3     [The mood created by the author is showing how...   
4     [The mood created in the memoir is happiness a...   
...                                                 ...   
1800  [The mood of this memoir is nonfiction., The m...   
1801  [The mood was created by the author in the mem...   
1802  [In the memoir "Narciso Rodriguez", the mood c...   
1803  [The mood created @CAPS3 the author, Narciso R...   
1804  [The author created such a specific mood for t...   

                                                   stem  \
0     [in, thi, memoir, of, narciso, rodriguez, ,, @...   
1     [throughout, the, excerpt, from, home, the, bl...   
2     [the, mood, the, author, creat, in, the, memoi...   
3     [the, mood, creat, by, the, author, is, show, ...   
4     [the, mood, creat, in, the, memoir, is, happi,...   
...                                                 ...   
1800  [the, mood, of, thi, memoir, is, nonfict, ., t...   
1801  [the, mood, wa, creat, by, the, author, in, th...   
1802  [in, the, memoir, ``, narciso, rodriguez, '', ...   
1803  [the, mood, creat, @, caps3, the, author, ,, n...   
1804  [the, author, creat, such, a, specif, mood, fo...   

                                                  lemma  
0     [In, this, memoir, of, Narciso, Rodriguez, ,, ...  
1     [Throughout, the, excerpt, from, Home, the, Bl...  
2     [The, mood, the, author, created, in, the, mem...  
3     [The, mood, created, by, the, author, is, show...  
4     [The, mood, created, in, the, memoir, is, happ...  
...                                                 ...  
1800  [The, mood, of, this, memoir, is, nonfiction, ...  
1801  [The, mood, wa, created, by, the, author, in, ...  
1802  [In, the, memoir, ``, Narciso, Rodriguez, '', ...  
1803  [The, mood, created, @, CAPS3, the, author, ,,...  
1804  [The, author, created, such, a, specific, mood...  

[1805 rows x 6 columns]

## 1. Skip-gram (Word2Vec) shortcut using `gensim`

In [42]:
#!pip install gensim
from gensim.models import Word2Vec


token_list = df['tokens'].values# this has to be a list that saves all the vocabulary 

print(token_list[:1])

model = Word2Vec(token_list, min_count=1,vector_size= 50,workers=3, window =2, sg = 1) # this is your model
# > vector_size: The number of dimensions of the embeddings and the default is 100.
# > window: The maximum distance between a target word and words around the target word. The default window is 5.
# > min_count: The minimum count of words to consider when training the model; words with occurrence less than this count will be ignored. The default for min_count is 5.
# > workers: The number of partitions during training and the default workers is 3.
# > sg: The training algorithm, either CBOW(0) or skip gram(1). The default training algorithm is CBOW.
    

[list(['In', 'this', 'memoir', 'of', 'Narciso', 'Rodriguez', ',', '@', 'PERSON3', "'s", 'life', ',', 'the', 'mood', 'containing', 'it', 'all', ',', 'was', 'greatful', ',', 'and', 'showed', 'how', 'his', 'parents', 'gave', 'him', 'love', 'through', 'his', 'whole', 'life', '.', 'Both', 'his', 'parents', 'were', 'born', 'and', 'raised', 'in', 'Cuba', ',', 'and', 'in', '1956', ',', 'they', 'both', 'moved', 'to', 'the', 'United', 'States', '.', 'Starting', 'their', 'lives', 'over', 'again', ',', 'and', 'taking', 'any', 'job', 'they', 'could', 'find', '.', 'Then', 'in', '1961', ',', '@', 'PERSON2', ',', '@', 'CAPS1', '.', 'was', 'born', '.', 'Both', 'Parents', 'raised', 'him', 'with', 'love', ',', 'and', 'care', ',', 'and', 'introducing', 'his', 'Cuban', 'background', 'into', 'his', 'life', '.', 'As', '@', 'PERSON2', ',', 'was', 'telling', 'his', 'story', ',', 'all', 'readers', 'could', 'tell', 'how', 'greatful', 'he', 'was', 'to', 'have', 'a', 'family', 'like', 'he', 'did', '.', 'Also', ','

array([-0.04510524,  0.26697066,  0.26178637, -0.09336256,  0.7100486 ,
       -0.50711715,  0.27854463,  0.41906863, -0.29762545,  0.09513719,
       -0.498547  , -0.48606616, -0.16202459, -0.31114635,  0.02056565,
        0.5335748 ,  0.46839586,  0.6353834 , -1.076645  , -0.5750287 ,
        0.7170416 ,  0.5854732 ,  0.07437601, -0.04927132,  0.29328343,
        0.2701225 ,  0.50601614, -0.65855676, -0.07047258, -0.22207823,
        0.05423851,  0.48059362,  0.21850856,  0.2510585 ,  0.13848186,
        0.53914315,  0.93614185, -0.06313057,  0.00417231,  0.0094842 ,
        0.52310115, -0.03271529, -0.4822553 , -0.20599154,  1.342623  ,
       -0.00356475, -0.59507424, -0.388651  ,  0.29877394,  0.42734957],
      dtype=float32)

In [ ]:
# let's explore

print(model.wv['author']) #this is to see the vector of a particular word 
print(model.wv['the'])

# dimension of the embeddings? 


In [59]:
# let's explore

#model.wv.most_similar('your token here') # to get the list of most similar tokens

(50,)

In [62]:
#let's explore 

# >> How to represent this essay into a vector then? 

example_essay = df.iloc[1].tokens
print(example_essay)

############ YOUR RESPONSE HERE ##################

#HINT: model.wv[example_essay[0]] This will give the embedding for the first token of the document 

result = [model.wv[i] for i in example_essay]
np.mean(result, axis=0)

##################################################


['Throughout', 'the', 'excerpt', 'from', 'Home', 'the', 'Blueprints', 'of', 'Our', 'Lives', ',', 'Narciso', 'Rodriguez', ',', 'the', 'author', ',', 'manages', 'to', 'maintain', 'a', 'single', 'overall', 'mood', '.', 'In', 'many', 'parts', 'of', 'the', 'story', 'he', 'tells', 'about', 'how', 'much', 'he', 'loved', 'his', 'childhood', 'so', 'it', 'lead', 'me', 'to', 'think', 'was', 'nostalgia', ',', 'but', 'nowhere', 'does', 'it', 'emphasize', 'that', 'he', 'yearns', 'to', 'return', 'to', 'past', 'times', '.', 'He', 'always', 'declared', 'how', 'loving', 'and', 'selfless', 'his', 'family', 'was', ',', 'how', 'they', 'aided', 'others', ',', 'and', 'how', 'he', 'became', "''", 'family', "''", 'with', 'his', 'neighbors', '.', 'Due', 'to', 'this', 'I', 'have', 'found', 'the', 'tone', 'to', 'be', ',', 'loving', 'and', 'admiring', 'towards', 'his', 'parents', '.', 'This', 'is', 'so', 'due', 'to', 'the', 'fact', 'that', 'he', 'states', 'how', 'his', 'parents', 'were', 'so', 'brave', 'to', 'leav

array([-0.09283703,  0.22092739,  0.08713946,  0.1767992 , -0.0684889 ,
       -0.32384235,  0.39595193,  0.56346333, -0.3686944 , -0.25329593,
        0.09150464, -0.43500766,  0.26115996,  0.13579236, -0.16134955,
        0.4430558 ,  0.40166396,  0.21252805, -0.43450668, -0.38708115,
        0.29850265,  0.46404812,  0.48952582, -0.00839027,  0.24992566,
        0.08442023,  0.01655283,  0.30153635, -0.2995487 ,  0.01725363,
        0.17147624, -0.21141139, -0.1303362 , -0.08280358, -0.03882691,
        0.20229356,  0.47468904,  0.15692674,  0.16440259, -0.21245219,
        0.4369847 , -0.19086793, -0.03272782, -0.13134383,  0.61550456,
        0.00832669,  0.03070776, -0.3663987 ,  0.20016785,  0.19245735],
      dtype=float32)

In [63]:

def average_embedding(model, document):
    normalizer = text_normalize()
    tokens = normalizer.tokenize(document )
  
    result = [model.wv[i] for i in tokens]
    
    return np.mean(result, axis=0)


In [68]:
## Let's explore your answer 
essay = df.response.values[2]

average_embedding(model, essay)

array([-0.09283703,  0.22092739,  0.08713946,  0.1767992 , -0.0684889 ,
       -0.32384235,  0.39595193,  0.56346333, -0.3686944 , -0.25329593,
        0.09150464, -0.43500766,  0.26115996,  0.13579236, -0.16134955,
        0.4430558 ,  0.40166396,  0.21252805, -0.43450668, -0.38708115,
        0.29850265,  0.46404812,  0.48952582, -0.00839027,  0.24992566,
        0.08442023,  0.01655283,  0.30153635, -0.2995487 ,  0.01725363,
        0.17147624, -0.21141139, -0.1303362 , -0.08280358, -0.03882691,
        0.20229356,  0.47468904,  0.15692674,  0.16440259, -0.21245219,
        0.4369847 , -0.19086793, -0.03272782, -0.13134383,  0.61550456,
        0.00832669,  0.03070776, -0.3663987 ,  0.20016785,  0.19245735],
      dtype=float32)

In [87]:
from sklearn.metrics.pairwise import cosine_similarity

def compare_similarity(documents):
    
    # use the average_embedding function you created above and a for-loop or a while-loop
    # to create a list called `embeddings`
    embeddings = []
    
    ############### your code here ##################
    for document in documents:
        embedding = average_embedding(model, document)
        embeddings.append([embedding])
    ################################################
    
    # compute the cosine similarity score of all pairs of the document list
    from itertools import combinations # you can use the combinations function 
    sim=0
    pairs = list(combinations(embeddings, 2))
    
    ############### your code here ##################
    for pair in pairs: 
        value = cosine_similarity(pair[0], pair[1])
        sim+=value
    
    ################################################
    return sim/len(pairs)

##############################################################################

# let's explore
essays = df.response.values[:2]
print(essays)

compare_similarity(essays)


["In this memoir of Narciso Rodriguez, @PERSON3's life, the mood containing it all, was greatful, and showed how his parents gave him love through his whole life. Both his parents were born and raised in Cuba, and in 1956, they both moved to the United States. Starting their lives over again, and taking any job they could find. Then in 1961, @PERSON2, @CAPS1. was born. Both Parents raised him with love, and care, and introducing his Cuban background into his life.        As @PERSON2, was telling his story, all readers could tell how greatful he was to have a family like he did. Also, as he shared his non-– blood related family, and the remembrence on how his parents' life changed by moving to @LOCATION2, he showed the respect he had towards them."
 'Throughout the excerpt from Home the Blueprints of Our Lives, Narciso Rodriguez, the author, manages to maintain a single overall mood. In many parts of the story he tells about how much he loved his childhood so it lead me to think was nos

array([[0.99065447]], dtype=float32)

## 4. Pre-trained GloVe Embeddings 
> Glove pre-trained word vectors are trained based on 6B tokens (400k vocabs) using Wikipedia 2014 and Gigaword 5. Various dimensions are availble (50d, 100d, 200d, & 300d).
More information avaialble at : https://nlp.stanford.edu/projects/glove/


In [72]:
class glove_embedding():
   
    def embedding(self, input_dir='./'):
        self.embeddings_index= []
        self.word_id = {}
        self.embeddings_index.append([0]*50)
        count=1
        f = open(input_dir+ 'glove.6B.50d.txt', encoding= 'utf8')
        for line in f:
            values = line.split()
            word = values[0]
            coefs =np.asarray(values[1:], dtype='float32') 
            self.word_id[word]= count
            self.embeddings_index.append(coefs) 
            count +=1
        f.close()

    def look_up(self, word):
        try: 
            word_id = self.word_id[word]
        
            return self.embeddings_index[word_id]
       
        except KeyError:
             print("Oops!  OOV.  Try again...")
            
    
glove = glove_embedding()
glove.embedding()

In [75]:
glove.look_up('trna')

array([ 0.51278 ,  0.25157 , -0.18394 , -0.014212,  0.98777 ,  0.67637 ,
        1.4479  , -0.69126 ,  0.42395 ,  0.98987 ,  0.52666 ,  0.47261 ,
        0.10964 ,  0.57513 ,  0.71705 ,  0.43191 ,  0.74033 ,  0.064138,
        0.6063  ,  0.88668 ,  0.45273 , -1.3187  ,  0.85178 ,  1.436   ,
       -0.85848 ,  0.15967 ,  0.57879 , -0.33475 ,  0.063739, -0.39744 ,
       -0.53869 , -1.198   , -0.78489 ,  0.62126 ,  1.5683  ,  0.35829 ,
        0.23824 , -0.17746 , -0.8014  ,  1.1288  ,  0.87474 , -0.25988 ,
        0.47701 ,  0.17045 , -0.18032 , -0.41559 ,  1.1162  ,  0.75873 ,
       -0.071018, -0.32746 ], dtype=float32)

In [76]:
glove.look_up('grna')

Oops!  OOV.  Try again...
